from futbotmx.level3.advanced_events import (
    RULE_VERSION as LEVEL3_ADVANCED_EVENTS_RULE_VERSION,
    AdvancedEventsConfig,
    ball_speed_segments,
    build_advanced_events,
    build_highlight_events,
    build_pass_chain_events,
    config_to_dict as advanced_events_config_to_dict,
    draw_highlight_overlay,
    load_level2_events,
    load_level2_possession_segments,
    possession_segments,
    score_highlight,
    write_level3_events,
    write_level3_highlights,
    write_narrative,
    write_overlay_validation,
)
from futbotmx.level3.dashboard import (
    RULE_VERSION as LEVEL3_DASHBOARD_RULE_VERSION,
    Level3DashboardConfig,
    build_dashboard,
    build_dashboard_context,
    config_to_dict as dashboard_config_to_dict,
    dashboard_manifest_rows,
    render_dashboard_html,
    write_dashboard_manifest,
)
from futbotmx.level3.clip_validation import (
    RULE_VERSION as ACTIVITY18_CLIP_VALIDATION_RULE_VERSION,
    ClipValidationSpec,
    build_activity18_package,
    build_validation_context,
    classify_outcome as classify_activity18_outcome,
    classify_visibility as classify_activity18_visibility,
)
from futbotmx.level3.executive_report import (
    RULE_VERSION as EXECUTIVE_REPORT_RULE_VERSION,
    ExecutiveReportConfig,
    build_executive_report_context,
    build_executive_report_package,
    config_to_dict as executive_report_config_to_dict,
    narrative_example,
    render_report_html,
)
from futbotmx.level3.final_report import (
    RULE_VERSION as FINAL_REPORT_RULE_VERSION,
    FinalReportConfig,
    build_final_report_context,
    build_final_report_package,
    config_to_dict as final_report_config_to_dict,
    final_report_manifest_rows,
    render_final_report_html,
    report_links,
    scan_heavy_outputs,
    validate_report_links,
)
from futbotmx.level3.highlight_review import (
    RULE_VERSION as HIGHLIGHT_REVIEW_RULE_VERSION,
    REVIEW_FIELDS as HIGHLIGHT_REVIEW_FIELDS,
    VALID_REVIEW_STATUSES,
    HighlightReviewConfig,
    build_highlight_review_context,
    build_highlight_review_package,
    build_review_rows,
    config_to_dict as highlight_review_config_to_dict,
    default_review_status,
    render_review_panel_html,
    validate_review_rows,
)
from futbotmx.level3.multiclip import (
    RULE_VERSION as LEVEL3_MULTICLIP_RULE_VERSION,
    COMPARISON_FIELDS,
    HUMAN_REVIEW_FIELDS,
    ClipMulticlipArtifacts,
    aggregate_review_status,
    build_human_review_rows,
    classify_review_status,
    limitation_flags,
    summarize_clip_artifacts,
    write_clip_human_review,
    write_multiclip_comparison,
    write_multiclip_manifest,
)
from futbotmx.level3.reel import (
    RULE_VERSION as LEVEL3_REEL_RULE_VERSION,
    Level3ReelConfig,
    build_reel_context,
    build_reel_package,
    config_to_dict as reel_config_to_dict,
    draw_contact_sheet,
    draw_reel_thumbnail,
    reel_manifest_rows,
    render_reel_demo_html,
    select_reel_segments,
)
from futbotmx.level3.schema import (
    LEVEL3_ARTIFACT_SCHEMAS,
    LEVEL3_EVENTS_FIELDS,
    LEVEL3_HIGHLIGHTS_FIELDS,
    LEVEL3_METRICS_FIELDS,
    LEVEL3_TRACKS_FIELDS,
    LEVEL3_VISUALIZATION_MANIFEST_FIELDS,
    ArtifactSchema,
    read_csv_artifact,
    schema_manifest_rows,
    schema_for_artifact,
    validate_required_fields,
    write_csv_artifact,
    write_schema_json,
    write_schema_manifest,
)
from futbotmx.level3.spatial import (
    RULE_VERSION as LEVEL3_SPATIAL_RULE_VERSION,
    ClipCalibration,
    ClipSpatialSpec,
    FieldModel,
    apply_homography_point,
    build_calibration_from_tracks,
    compare_calibrations,
    draw_minimap_base,
    draw_minimap_tracks,
    estimate_manual_calibration_confidence,
    normalized_zone,
    polygon_area,
    read_level3_tracks,
    read_spatial_tracks,
    rectify_track_rows,
    solve_homography,
    summarize_rectified_tracks,
    write_calibration_comparison_csv,
    transform_point_with_calibration,
    write_calibration_json,
    write_level3_tracks,
    write_spatial_tracks,
    write_spatial_validation_csv,
)
from futbotmx.level3.tactical import (
    RULE_VERSION as LEVEL3_TACTICAL_RULE_VERSION,
    TacticalConfig,
    aggregate_control_by_clip,
    aggregate_control_by_team,
    aggregate_interaction_edges,
    build_interaction_graph,
    build_level3_metric_rows,
    compute_interactions,
    compute_spatial_control,
    compute_tactical_outputs,
    config_to_dict as tactical_config_to_dict,
    euclidean_norm,
    grid_cells,
    interaction_samples_for_frame,
    is_ball,
    is_robot,
    spatial_control_for_frame,
    usable_track,
    write_interaction_edges,
    write_interaction_metrics,
    write_level3_metrics_csv,
    write_level3_metrics_json,
    write_spatial_control_csv,
    write_voronoi_frames_csv,
)
from futbotmx.level3.team_assignment import (
    RULE_VERSION as TEAM_ASSIGNMENT_RULE_VERSION,
    TEAM_ASSIGNMENT_FIELDS,
    TeamAssignmentConfig,
    apply_team_assignments,
    build_team_assignment_package,
    build_team_assignments,
    config_to_dict as team_assignment_config_to_dict,
    evaluate_assignment_strategies,
    robot_track_summaries,
    write_json_summary as write_team_assignment_json_summary,
    write_team_assignment_csv,
)
from futbotmx.level3.visualizations import (
    RULE_VERSION as LEVEL3_VISUALIZATIONS_RULE_VERSION,
    Level3VisualizationConfig,
    build_visualizations,
    config_to_dict as visualization_config_to_dict,
    draw_interaction_graph,
    draw_minimap_highlight,
    draw_storyboard,
    draw_voronoi_minimap,
    draw_voronoi_original_overlay,
    find_level2_overlay,
    write_storyboard_manifest,
    write_visualization_manifest,
)
from futbotmx.level3.video_overlay import (
    RULE_VERSION as VIDEO_OVERLAY_RULE_VERSION,
    VideoOverlayConfig,
    build_video_overlay_context,
    build_video_overlay_package,
    config_to_dict as video_overlay_config_to_dict,
    select_overlay_segments,
    video_overlay_manifest_rows,
)

__all__ = [
    "AdvancedEventsConfig",
    "ACTIVITY18_CLIP_VALIDATION_RULE_VERSION",
    "ArtifactSchema",
    "COMPARISON_FIELDS",
    "ClipCalibration",
    "ClipMulticlipArtifacts",
    "ClipValidationSpec",
    "ClipSpatialSpec",
    "FieldModel",
    "EXECUTIVE_REPORT_RULE_VERSION",
    "FINAL_REPORT_RULE_VERSION",
    "HUMAN_REVIEW_FIELDS",
    "HIGHLIGHT_REVIEW_FIELDS",
    "HIGHLIGHT_REVIEW_RULE_VERSION",
    "LEVEL3_ADVANCED_EVENTS_RULE_VERSION",
    "LEVEL3_ARTIFACT_SCHEMAS",
    "LEVEL3_DASHBOARD_RULE_VERSION",
    "LEVEL3_EVENTS_FIELDS",
    "LEVEL3_HIGHLIGHTS_FIELDS",
    "LEVEL3_METRICS_FIELDS",
    "LEVEL3_MULTICLIP_RULE_VERSION",
    "LEVEL3_REEL_RULE_VERSION",
    "LEVEL3_SPATIAL_RULE_VERSION",
    "LEVEL3_TACTICAL_RULE_VERSION",
    "LEVEL3_TRACKS_FIELDS",
    "LEVEL3_VISUALIZATION_MANIFEST_FIELDS",
    "LEVEL3_VISUALIZATIONS_RULE_VERSION",
    "TEAM_ASSIGNMENT_FIELDS",
    "TEAM_ASSIGNMENT_RULE_VERSION",
    "VIDEO_OVERLAY_RULE_VERSION",
    "ExecutiveReportConfig",
    "FinalReportConfig",
    "Level3DashboardConfig",
    "Level3ReelConfig",
    "Level3VisualizationConfig",
    "HighlightReviewConfig",
    "TacticalConfig",
    "TeamAssignmentConfig",
    "VideoOverlayConfig",
    "advanced_events_config_to_dict",
    "aggregate_control_by_clip",
    "aggregate_control_by_team",
    "aggregate_interaction_edges",
    "aggregate_review_status",
    "apply_team_assignments",
    "apply_homography_point",
    "ball_speed_segments",
    "build_human_review_rows",
    "build_highlight_review_context",
    "build_highlight_review_package",
    "build_executive_report_context",
    "build_executive_report_package",
    "build_final_report_context",
    "build_final_report_package",
    "build_advanced_events",
    "build_activity18_package",
    "build_dashboard",
    "build_dashboard_context",
    "build_highlight_events",
    "build_interaction_graph",
    "build_calibration_from_tracks",
    "compare_calibrations",
    "build_level3_metric_rows",
    "build_pass_chain_events",
    "build_reel_context",
    "build_review_rows",
    "build_reel_package",
    "build_team_assignment_package",
    "build_team_assignments",
    "build_visualizations",
    "build_validation_context",
    "build_video_overlay_context",
    "build_video_overlay_package",
    "classify_review_status",
    "classify_activity18_outcome",
    "classify_activity18_visibility",
    "dashboard_config_to_dict",
    "default_review_status",
    "dashboard_manifest_rows",
    "executive_report_config_to_dict",
    "final_report_config_to_dict",
    "final_report_manifest_rows",
    "compute_interactions",
    "compute_spatial_control",
    "compute_tactical_outputs",
    "draw_minimap_base",
    "draw_minimap_tracks",
    "estimate_manual_calibration_confidence",
    "evaluate_assignment_strategies",
    "draw_highlight_overlay",
    "draw_interaction_graph",
    "draw_minimap_highlight",
    "draw_contact_sheet",
    "draw_reel_thumbnail",
    "draw_storyboard",
    "draw_voronoi_minimap",
    "draw_voronoi_original_overlay",
    "euclidean_norm",
    "find_level2_overlay",
    "grid_cells",
    "interaction_samples_for_frame",
    "is_ball",
    "is_robot",
    "limitation_flags",
    "load_level2_events",
    "load_level2_possession_segments",
    "narrative_example",
    "normalized_zone",
    "polygon_area",
    "possession_segments",
    "read_csv_artifact",
    "read_level3_tracks",
    "read_spatial_tracks",
    "rectify_track_rows",
    "reel_config_to_dict",
    "reel_manifest_rows",
    "render_dashboard_html",
    "render_final_report_html",
    "render_report_html",
    "render_review_panel_html",
    "render_reel_demo_html",
    "report_links",
    "robot_track_summaries",
    "scan_heavy_outputs",
    "schema_manifest_rows",
    "schema_for_artifact",
    "score_highlight",
    "select_reel_segments",
    "select_overlay_segments",
    "solve_homography",
    "spatial_control_for_frame",
    "summarize_rectified_tracks",
    "summarize_clip_artifacts",
    "tactical_config_to_dict",
    "team_assignment_config_to_dict",
    "highlight_review_config_to_dict",
    "transform_point_with_calibration",
    "usable_track",
    "validate_report_links",
    "validate_required_fields",
    "validate_review_rows",
    "VALID_REVIEW_STATUSES",
    "video_overlay_config_to_dict",
    "video_overlay_manifest_rows",
    "visualization_config_to_dict",
    "write_calibration_json",
    "write_calibration_comparison_csv",
    "write_csv_artifact",
    "write_dashboard_manifest",
    "write_interaction_edges",
    "write_interaction_metrics",
    "write_clip_human_review",
    "write_level3_events",
    "write_level3_highlights",
    "write_level3_metrics_csv",
    "write_level3_metrics_json",
    "write_level3_tracks",
    "write_spatial_tracks",
    "write_multiclip_comparison",
    "write_multiclip_manifest",
    "write_narrative",
    "write_overlay_validation",
    "write_schema_json",
    "write_schema_manifest",
    "write_spatial_control_csv",
    "write_spatial_validation_csv",
    "write_storyboard_manifest",
    "write_team_assignment_csv",
    "write_team_assignment_json_summary",
    "write_visualization_manifest",
    "write_voronoi_frames_csv",
]
